<?php
/**
 * Created by PhpStorm.
 * User: alexey_baranov
 * Date: 23.08.14
 * Time: 19:37
 */

class MessageTest extends PHPUnit_Framework_TestCase {
    /**
     * @var \MailEx\Message
     */
    public $object;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->object = new \MailEx\Message();
    }



    public function testSetHtmlBody()
    {
        $this->object->setHtmlBody("<br><br>");
    }


    public function testSetDefaultFrom()
    {
        \MailEx\Message::setDefaultFrom("alexey_baranov@inbox.ru", "Алексей Баранов");
    }





}
 